apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhnmrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhnmrt
  template:
    metadata:
      labels:
        app: dhnmrt
    spec:
      containers:
      - image: okteto.dev/dhnmrt:latest
        name: dhnmrt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "29a84b43-84a5-4069-89b3-40730623f986"
        - name: Vless_Path
          value: "/vl3bh45"
        - name: Vmess_UUID
          value: "29a84b43-84a5-4069-89b3-40730623f986"
        - name: Vmess_Path
          value: "/vm89jy6"
        - name: Share_Path
          value: "/v2link"
